#!/bin/sh
# If the user is not root
# if [ "$USERNAME" != "root" ]; then
#   # Dislpay a notice and stop
#   echo "Sorry, only root can use this command." exit 1
#   exit 1
# fi

echo "Paste the SSH Public key to add:"; read key
keyfile=$(tempfile)
echo "$key" > $keyfile

# Generate a fingerprint
fingerprint=$(ssh-keygen -lf $keyfile)

# Check for errors
if [ $(echo "$fingerprint" | egrep -c '(R|D)SA') -eq 0 ]; then
  # Dislpay a notice and stop
  echo "Error: $fingerprint"
  rm $keyfile
  exit 1
fi

# Add the key to the authorized_keys file and clean up
mkir -p .ssh
echo -n "no-agent-forwarding,no-port-forwarding,no-X11-forwarding " >> .ssh/authorized_keys
cat $keyfile >> .ssh/authorized_keys
rm $keyfile

# Display the fingerprint for reference
echo "Success! Added a key with this fingerprint: "
echo $fingerprint
