#!/bin/sh
echo "Run 'help' for a list of commands, or 'exit' to leave.  Available commands:"
echo "addkey - Add an OpenSSH key to the authorized_keys file."
echo "create - Create a git repository."
echo "delete - Delete a git repository."
echo "list   - List git repositories on this system."

